### ISSUE TITLE
Automatically insert linebrakes / make font smaller to prevent too large pages

### ISSUE THREAD

**Issue by jtagcat** [janesmae/signs_at_k-space#4]
![image](https://user-images.githubusercontent.com/38327267/76460670-56e1a100-63d6-11ea-9cbd-d36998112a8a.png)
just buy ultrawide printer and paper ( ͡° ͜ʖ ͡°)

**Comment by janesmae** [comment]
Just wondering, what are the use-cases for very long words? Planning and event named "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch" ?

**Comment by jtagcat** [comment]
Did it work with long sentences on one line? I think it didn't.
/shrug signs are not really for events, but for 'if you do this, you'll kill yourself or your wallet'

**Comment by janesmae** [comment]
It works with text. Maybe it does not work with unicode.

<img width="1293" alt="Screenshot 2020-03-13 at 02 56 06" src="https://user-images.githubusercontent.com/2997606/76579913-9a233900-64d6-11ea-8dc9-e0b8bc40909d.png">
<img width="1260" alt="Screenshot 2020-03-13 at 02 58 22" src="https://user-images.githubusercontent.com/2997606/76579922-a14a4700-64d6-11ea-9dec-ac3984bd6d4f.png">

**Comment by janesmae** [comment]
Also, a side note: I wrote this little webpage, so I could produce constant easy results for ChaosTreff door sings (at a time when I was still organising those) without having an OpenOffice template (that i can potentially loose). The use case of unicode and a lot of it is one of those edge cases where I would have to claim that if it bothers you, fix it.

Sorry, but I have to be blatant.

**Comment by jtagcat** [comment]
Good Morning‽ (should probably go to sleep now)

I was talking about before, nvm.

I love that I open an issue here and get a notification of 'solved'. How to code :upside_down_face: 

Though if I want to complain, the subtext still extends the page, instead of changing the font smaller.

I'd say it's not only useful for Chaostreff, also for 'don't you dare kill yourself with that' and even outside of k-space (inspecto elemento, deleto logo; could be a toggle / something more user-friendly than inspectiano elementono to replace the logo and cope with different aspect ratios)

**Comment by janesmae** [comment]
I have a strong sense of ownership for my projects, also solving issues is kind of fun. That is why I'm doing those changes. But this is a topic for another time.

I'm aware of the subtext issue and it is a simple fix, I wanted to get the all clear or the main area before going one step further.

And yes, it is useful for more purposes. Just my 2 cents on why I coded that. Once upon a time I had plans and visions for many things, many small improvements on simple things. Maybe one day ...

**Comment by jtagcat** [comment]
last part hits home too hard
